kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - custom

steps:
  - name: build-image
    image: docker:24
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t chat-app:${DRONE_BUILD_NUMBER} -t chat-app:latest .

  - name: deploy
    image: docker:24
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - IMAGE_TAG=${DRONE_BUILD_NUMBER} docker compose up -d --force-recreate

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
